#!/usr/bin/env python3
import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "main" / "ime" / "seg_table_source.txt"
OUT = ROOT / "main" / "ime" / "seg_table.h"


def parse_source(path):
    entries = []
    seen = set()
    for line_no, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "\t" not in line:
            raise SystemExit(f"{path}:{line_no}: expected syllables<TAB>word")
        syllables, word = line.split("\t", 1)
        syllables = " ".join(syllables.strip().split())
        word = word.strip()
        if not syllables or not word:
            raise SystemExit(f"{path}:{line_no}: empty syllables or word")
        for syl in syllables.split(" "):
            if not syl.isascii() or not syl.isalpha() or not syl.islower():
                raise SystemExit(f"{path}:{line_no}: invalid syllable {syl!r}")
        key = (syllables, word)
        if key in seen:
            continue
        seen.add(key)
        entries.append(key)
    return entries


def escape_c(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def render(entries):
    lines = [
        "#pragma once",
        "// Generated by scripts/generate_seg_table.py from main/ime/seg_table_source.txt.",
        "// Pinyin segmentation supplement dictionary.",
        "struct SegEntry {",
        "    const char *syllables;",
        "    const char *word;",
        "};",
        "",
        "static const SegEntry SEG_TABLE[] = {",
    ]
    for syllables, word in entries:
        lines.append(f'    {{ "{escape_c(syllables)}", "{escape_c(word)}" }},')
    lines.extend([
        "};",
        "",
        "static const int SEG_TABLE_COUNT = (int)(sizeof(SEG_TABLE) / sizeof(SEG_TABLE[0]));",
        "",
    ])
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description="Generate seg_table.h from seg_table_source.txt.")
    ap.add_argument("--check", action="store_true", help="fail if generated output differs")
    args = ap.parse_args()

    text = render(parse_source(SRC))
    if args.check:
        current = OUT.read_text(encoding="utf-8")
        if current != text:
            raise SystemExit("seg_table.h is out of date; run scripts/generate_seg_table.py")
        return
    OUT.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
