#!/usr/bin/env python3
import argparse
from collections import OrderedDict
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SEED = ROOT / "main" / "ime" / "predict_source.txt"
DEFAULT_SEG = ROOT / "main" / "ime" / "seg_table_source.txt"


def add_candidate(groups, key, word, limit):
    if not (1 <= len(key) <= 4 and 1 <= len(word) <= 4):
        return
    if key not in groups:
        groups[key] = []
    if word not in groups[key] and len(groups[key]) < limit:
        groups[key].append(word)


def load_seed(path, limit):
    groups = OrderedDict()
    if not path.exists():
        return groups
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "\t" in line:
            key, rest = line.split("\t", 1)
            words = rest.replace("\t", " ").split()
        else:
            parts = line.split()
            if len(parts) < 2:
                continue
            key, words = parts[0], parts[1:]
        for word in words:
            add_candidate(groups, key.strip(), word.strip(), limit)
    return groups


def augment_from_seg(groups, path, limit):
    seen_words = set()
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "\t" not in line:
            continue
        _, word = line.split("\t", 1)
        word = word.strip()
        if word in seen_words or len(word) < 2:
            continue
        seen_words.add(word)
        max_key_len = min(4, len(word) - 1)
        for key_len in range(max_key_len, 0, -1):
            key = word[:key_len]
            tail = word[key_len:key_len + 4]
            add_candidate(groups, key, tail, limit)


def write_source(groups, path):
    lines = [
        "# Generated by scripts/generate_predict_source.py.",
        "# key<TAB>candidate...",
        "# Candidates are UTF-8 CJK text, separated by spaces or tabs.",
    ]
    for key, words in groups.items():
        if words:
            lines.append(f"{key}\t{' '.join(words)}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    ap = argparse.ArgumentParser(description="Generate IME prediction source from seeds and phrase table.")
    ap.add_argument("--seed", default=str(DEFAULT_SEED))
    ap.add_argument("--seg", default=str(DEFAULT_SEG))
    ap.add_argument("--output", default=str(DEFAULT_SEED))
    ap.add_argument("--limit", type=int, default=16)
    args = ap.parse_args()

    groups = load_seed(Path(args.seed), args.limit)
    augment_from_seg(groups, Path(args.seg), args.limit)
    write_source(groups, Path(args.output))
    print(f"wrote {args.output}: {len(groups)} groups")


if __name__ == "__main__":
    main()
