#!/usr/bin/env python3
import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "main" / "ime" / "seg_table_source.txt"
OUT = ROOT / "main" / "ime" / "seg_table.h"


def parse_source(path):
    entries = []
    seen = set()
    for line_no, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "\t" not in line:
            raise SystemExit(f"{path}:{line_no}: expected syllables<TAB>word")
        syllables, word = line.split("\t", 1)
        syllables = " ".join(syllables.strip().split())
        word = word.strip()
        if not syllables or not word:
            raise SystemExit(f"{path}:{line_no}: empty syllables or word")
        for syl in syllables.split(" "):
            if not syl.isascii() or not syl.isalpha() or not syl.islower():
                raise SystemExit(f"{path}:{line_no}: invalid syllable {syl!r}")
        key = (syllables, word)
        if key in seen:
            continue
        seen.add(key)
        entries.append(key)
    return entries


def escape_c(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def initial_of(syllable, keep_zh_ch_sh):
    if keep_zh_ch_sh and syllable[:2] in ("zh", "ch", "sh"):
        return syllable[:2]
    return syllable[:1]


def render(entries):
    enriched = []
    for source_idx, (syllables, word) in enumerate(entries):
        parts = syllables.split(" ")
        code = "".join(parts)
        initial = "".join(initial_of(s, True) for s in parts)
        compact_initial = "".join(initial_of(s, False) for s in parts)
        enriched.append((source_idx, syllables, code, initial, compact_initial, len(parts), word))

    def prefix_key(text):
        if not text:
            return 26 * 26
        c0 = ord(text[0]) - ord("a")
        if c0 < 0 or c0 >= 26:
            return 26 * 26
        if len(text) == 1:
            return c0 * 26
        c1 = ord(text[1]) - ord("a")
        if c1 < 0 or c1 >= 26:
            return 26 * 26
        return c0 * 26 + c1

    def build_order_and_index(field_idx):
        ordered = sorted(enriched, key=lambda item: (item[field_idx], item[0]))
        counts = [0] * (26 * 26)
        for item in ordered:
            k = prefix_key(item[field_idx])
            if k < len(counts):
                counts[k] += 1
        index = [0]
        total = 0
        for count in counts:
            total += count
            index.append(total)
        return [item[0] for item in ordered], index

    code_order, code_index = build_order_and_index(2)
    initial_order, initial_index = build_order_and_index(3)
    compact_initial_order, compact_initial_index = build_order_and_index(4)

    def render_u16_array(name, values, per_line=16):
        out = [f"static const uint16_t {name}[] = {{"]
        for i in range(0, len(values), per_line):
            chunk = ", ".join(str(v) for v in values[i:i + per_line])
            out.append(f"    {chunk},")
        out.append("};")
        return out

    lines = [
        "#pragma once",
        "// Generated by scripts/generate_seg_table.py from main/ime/seg_table_source.txt.",
        "// Pinyin segmentation supplement dictionary.",
        "#include <stdint.h>",
        "",
        "struct SegEntry {",
        "    const char *syllables;",
        "    const char *code;",
        "    const char *initial;",
        "    const char *compactInitial;",
        "    uint8_t syllableCount;",
        "    const char *word;",
        "};",
        "",
        "static const SegEntry SEG_TABLE[] = {",
    ]
    for _, syllables, code, initial, compact_initial, syllable_count, word in enriched:
        lines.append(
            f'    {{ "{escape_c(syllables)}", "{escape_c(code)}", '
            f'"{escape_c(initial)}", "{escape_c(compact_initial)}", '
            f'{syllable_count}, "{escape_c(word)}" }},'
        )
    lines.extend([
        "};",
        "",
        "static const int SEG_TABLE_COUNT = (int)(sizeof(SEG_TABLE) / sizeof(SEG_TABLE[0]));",
        "",
    ])
    lines.extend(render_u16_array("SEG_CODE_ORDER", code_order))
    lines.append("")
    lines.extend(render_u16_array("SEG_CODE_INDEX", code_index))
    lines.append("")
    lines.extend(render_u16_array("SEG_INITIAL_ORDER", initial_order))
    lines.append("")
    lines.extend(render_u16_array("SEG_INITIAL_INDEX", initial_index))
    lines.append("")
    lines.extend(render_u16_array("SEG_COMPACT_INITIAL_ORDER", compact_initial_order))
    lines.append("")
    lines.extend(render_u16_array("SEG_COMPACT_INITIAL_INDEX", compact_initial_index))
    lines.append("")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description="Generate seg_table.h from seg_table_source.txt.")
    ap.add_argument("--check", action="store_true", help="fail if generated output differs")
    args = ap.parse_args()

    text = render(parse_source(SRC))
    if args.check:
        current = OUT.read_text(encoding="utf-8")
        if current != text:
            raise SystemExit("seg_table.h is out of date; run scripts/generate_seg_table.py")
        return
    OUT.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
