#!/usr/bin/env python3
"""Prepare a pjournal firmware release.

Default behavior is local-only: update version strings, run IME checks, build,
merge firmware, and copy versioned artifacts. Git commit/push/GitHub release are
opt-in so ordinary release prep cannot publish by accident.
"""

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def run(cmd, *, shell=False):
    if shell:
        print(f"==> {cmd}", flush=True)
        subprocess.run(cmd, cwd=ROOT, shell=True, executable="/bin/bash", check=True)
    else:
        print("==>", " ".join(str(c) for c in cmd), flush=True)
        subprocess.run([str(c) for c in cmd], cwd=ROOT, check=True)


def update_text(path, pattern, repl):
    text = path.read_text(encoding="utf-8")
    new, count = re.subn(pattern, repl, text)
    if count == 0:
        raise SystemExit(f"{path}: version pattern not found")
    path.write_text(new, encoding="utf-8")


def update_versions(version):
    update_text(
        ROOT / "main" / "CMakeLists.txt",
        r'PJOURNAL_VERSION="[0-9]+\.[0-9]+\.[0-9]+"',
        f'PJOURNAL_VERSION="{version}"',
    )
    update_text(
        ROOT / "README.md",
        r"当前版本: v[0-9]+\.[0-9]+\.[0-9]+",
        f"当前版本: v{version}",
    )


def build(build_dir):
    run(f". /home/ywz/esp-idf/export.sh >/dev/null && cmake --build {build_dir} -j2",
        shell=True)


def merge(build_dir):
    build = ROOT / build_dir
    run([
        "esptool.py", "--chip", "esp32s3", "merge_bin",
        "-o", build / "pjournal-merged.bin",
        "--flash_mode", "dio",
        "--flash_size", "16MB",
        "--flash_freq", "80m",
        "0x0", build / "bootloader" / "bootloader.bin",
        "0x8000", build / "partition_table" / "partition-table.bin",
        "0x10000", build / "pjournal.bin",
    ])


def copy_artifacts(version, build_dir):
    build = ROOT / build_dir
    app = ROOT / f"pjournal-{version}.bin"
    merged = ROOT / f"pjournal-{version}-merged.bin"
    shutil.copy2(build / "pjournal.bin", app)
    shutil.copy2(build / "pjournal-merged.bin", merged)
    shutil.copy2(merged, ROOT / "pjournal-merged.bin")
    return app, merged


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("version", help="semantic version, e.g. 4.9.1")
    ap.add_argument("--build-dir", default="build-yong-ime")
    ap.add_argument("--skip-checks", action="store_true")
    ap.add_argument("--commit", action="store_true")
    ap.add_argument("--push", action="store_true")
    ap.add_argument("--github-release", action="store_true")
    args = ap.parse_args()

    if not re.fullmatch(r"\d+\.\d+\.\d+", args.version):
        raise SystemExit("version must look like 4.9.1")

    update_versions(args.version)
    if not args.skip_checks:
        run([sys.executable, ROOT / "scripts" / "check_ime_all.py"])
        run(["git", "diff", "--check"])
    build(args.build_dir)
    merge(args.build_dir)
    app, merged = copy_artifacts(args.version, args.build_dir)
    run([sys.executable, ROOT / "scripts" / "firmware_size_report.py", "--build-dir", args.build_dir])

    tag = f"v{args.version}"
    if args.commit:
        run(["git", "add", "README.md", "main/CMakeLists.txt"])
        run(["git", "commit", "-m", f"Release {tag}"])
        run(["git", "tag", tag])
    if args.push:
        run(["git", "push", "origin", "main"])
        run(["git", "push", "origin", tag])
    if args.github_release:
        notes = (
            f"## {tag}\n\n"
            "- Firmware release generated by scripts/release.py.\n\n"
            "Firmware:\n"
            f"- `{app.name}`: app image\n"
            f"- `{merged.name}`: merged image for flashing at offset 0x0\n"
        )
        run([
            "gh", "release", "create", tag, app, merged,
            "--title", tag,
            "--notes", notes,
        ])


if __name__ == "__main__":
    main()
